COMMENTS_SIZE = 7
GET_ANALYSIS_OF_TIME = 7
GET_ANALYSIS_OF_LANGUAGES = 8
GET_ANALYSIS_OF_EMOTION = 9
GET_ANALYSIS_OF_LIKES_VS_REPLIES = 10
GET_ANALYSIS_OF_NEQ_POS = 11
GET_POPULARITY = 12
GET_WORD_MAP = 13
