# Generated by Django 4.2.11 on 2024-05-04 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField()),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('subscriber_count', models.IntegerField()),
                ('title', models.TextField()),
                ('video_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_channel',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('like_count', models.IntegerField()),
                ('published_at', models.DateTimeField()),
                ('view_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('language', models.TextField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='video', to='MainApp.channel')),
            ],
            options={
                'db_table': 'tb_video',
            },
        ),
        migrations.CreateModel(
            name='VideoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_group', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(related_name='video_group', to='MainApp.video')),
            ],
            options={
                'db_table': 'tb_video_group',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('date_completion', models.DateTimeField()),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_request',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('author_display_name', models.TextField()),
                ('like_count', models.IntegerField()),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('total_reply_count', models.IntegerField()),
                ('replies', models.ManyToManyField(to='MainApp.comment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='MainApp.video')),
            ],
            options={
                'db_table': 'tb_comment',
            },
        ),
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('channel', models.ManyToManyField(related_name='channel_group', to='MainApp.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_channel_group',
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calculation_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_calculation_result',
            },
        ),
    ]
